USER_NAME := hedgestock

LTO_ENABLE = yes
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
WEBUSB_ENABLE = no
ORYX_ENABLE = no
RGBLIGHT_ENABLE = no
MIDI_ENABLE = no
NKRO_ENABLE = no
AUDIO_ENABLE = no # To test
STENO_ENABLE = no
EXTRAKEY_ENABLE = yes
COMBO_ENABLE = no
CONSOLE_ENABLE = no